# Generated by Django 5.2.5 on 2026-04-02 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('qurilish', "Qurilish va ta'mirlash"), ('yuk_tashish', "Yuk tashish va ko'chirish"), ('tozalash', 'Tozalash xizmati'), ('qishloq', "Qishloq xo'jaligi"), ('savdo', 'Savdo va xizmat'), ('it', 'IT va kompyuter'), ("ta'lim", "Ta'lim va repetitorlik"), ("sog'liqni_saqlash", "Sog'liqni saqlash"), ('cafe', 'Cafe va restoran'), ('boshqa', 'Boshqa')], default='boshqa', max_length=50)),
                ('salary', models.DecimalField(decimal_places=0, help_text="So'mda", max_digits=12)),
                ('salary_type', models.CharField(choices=[('kunlik', 'Kunlik'), ('soatlik', 'Soatlik'), ('loyiha', 'Loyiha')], default='kunlik', max_length=20)),
                ('region', models.CharField(choices=[('toshkent_shahar', 'Toshkent shahri'), ('toshkent_viloyat', 'Toshkent viloyati'), ('andijon', 'Andijon viloyati'), ('fargona', "Farg'ona viloyati"), ('namangan', 'Namangan viloyati'), ('samarqand', 'Samarqand viloyati'), ('buxoro', 'Buxoro viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('jizzax', 'Jizzax viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('navoiy', 'Navoiy viloyati'), ('xorazm', 'Xorazm viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], default='toshkent_shahar', max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='job_images/')),
                ('workers_needed', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ochiq', 'Ochiq'), ('yopiq', 'Yopiq'), ('tugallangan', 'Tugallangan')], default='ochiq', max_length=20)),
                ('work_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('qabul_qilindi', 'Qabul qilindi'), ('rad_etildi', 'Rad etildi')], default='kutilmoqda', max_length=20)),
                ('message', models.TextField(blank=True, help_text="Qo'shimcha xabar (ixtiyoriy)", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job', 'worker')},
            },
        ),
    ]
