# Generated by Django 5.2.5 on 2026-04-02 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('worker', 'Ishchi'), ('employer', 'Ish beruvchi')], default='worker', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('region', models.CharField(blank=True, choices=[('toshkent_shahar', 'Toshkent shahri'), ('toshkent_viloyat', 'Toshkent viloyati'), ('andijon', 'Andijon viloyati'), ('fargona', "Farg'ona viloyati"), ('namangan', 'Namangan viloyati'), ('samarqand', 'Samarqand viloyati'), ('buxoro', 'Buxoro viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('jizzax', 'Jizzax viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('navoiy', 'Navoiy viloyati'), ('xorazm', 'Xorazm viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
